name: web deploy by ftp
on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: "10.x" # set this to the node version to use

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          npm install
          npm run build:stage --if-present
          # npm run test --if-present

      - name: 静态发布
      - uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: serfend.top
          FTP_USERNAME: ${{ secrets.FTP_PASSWORD }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./dist
          REMOTE_DIR: /kitsune
          ARGS: --delete --transfer-all --exclude=logreport --verbose
